// Add/create a user
POST http://localhost:3001/users/add
Content-type: application/json

{
    "username": "Pelle",
    "password": "123"
}

###

// Login in user
POST http://localhost:3001/users/login
Content-Type: application/json

{
    "username": "Evelina",
    "password": "123"
}

###

DELETE http://localhost:3001/users/logout